'use strict';
const $=s=>document.querySelector(s);
const wordCount=t=>(t.match(/\S+/gu)||[]).filter(w=>/[\p{L}\p{N}]/u.test(w)).length;
const fmt=n=>new Intl.NumberFormat('en',{maximumFractionDigits:6}).format(n);
let category='All';function filter(){const q=($('#search')?.value||'').toLowerCase();let n=0;document.querySelectorAll('.toolcard').forEach(c=>{const show=(category==='All'||c.dataset.category===category)&&c.dataset.name.includes(q);c.hidden=!show;if(show)n++});if($('#empty'))$('#empty').hidden=n>0;}
$('#search')?.addEventListener('input',filter);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});filter()}));
const workspace=$('.workspace');
if(workspace&&!['gpa-calculator','flashcard-maker','number-converter','cover-page-maker','exam-planner','attendance-calculator'].includes(workspace.dataset.tool)){const type=workspace.dataset.tool, controls=$('#controls'),result=$('#result');
const field=(id,label,value='',attrs='')=>`<label>${label}<input id="${id}" type="number" step="any" value="${value}" ${attrs}></label>`;
const select=(id,label,options)=>`<label>${label}<select id="${id}">${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
const output=t=>{result.classList.remove('error');result.textContent=t;return t};
const number=id=>{let raw=$('#'+id).value;if(raw.trim()==='')throw Error('Please fill in every number.');let n=Number(raw);if(!Number.isFinite(n))throw Error('Enter finite numbers.');return n};
const pct=(n,label)=>{if(n<0||n>100)throw Error(label+' must be between 0 and 100.');return n};
const run=fn=>{try{return fn()}catch(e){result.classList.add('error');result.textContent=e.message;return {error:e.message}}};
const button=(id,text)=>`<button type="button" id="${id}" class="primary">${text}</button>`;
let calculate;
if(['word-counter','case-converter','text-cleaner','reading-time'].includes(type)){
controls.innerHTML='<label for="text">Your text</label><textarea id="text" placeholder="Paste or type your text here…"></textarea>'+(type==='reading-time'?'<div class="fields">'+field('pace','Words per minute',130,'min="1" max="1000"')+'</div>':'')+'<div class="actions">'+(type==='case-converter'?['Uppercase','Lowercase','Title case','Sentence case'].map((x,i)=>`<button type="button" data-case="${i}">${x}</button>`).join(''):type==='text-cleaner'?button('clean','Clean text'):'')+'<button type="button" id="copy">Copy text</button><button type="button" id="clear">Clear</button></div>';
calculate=()=>{const t=$('#text').value,w=wordCount(t);if(type==='word-counter'){result.classList.remove('error');result.innerHTML='<div class="metrics">'+[[w,'Words'],[Array.from(t).length,'Characters'],[t.trim()?t.trim().split(/\n\s*\n/u).length:0,'Paragraphs'],[fmt(w/200)+' min','Reading at 200 wpm']].map(([n,l])=>`<div class="metric"><strong>${n}</strong><span>${l}</span></div>`).join('')+'</div>';return {words:w,characters:Array.from(t).length}}if(type==='reading-time'){let p=number('pace');if(p<=0||p>1000)throw Error('Choose a pace between 1 and 1,000 words per minute.');return output(`${w} words · ${fmt(w/p)} minutes\nEstimate = ${w} ÷ ${p}. Add time for pauses and questions.`)}return output(`${w} words · ${Array.from(t).length} characters. ${type==='text-cleaner'?'Choose Clean text to tidy spacing.':'Choose a case above to transform your text.'}`)};
$('#text').addEventListener('input',()=>run(calculate));$('#pace')?.addEventListener('input',()=>run(calculate));$('#clear').onclick=()=>{$('#text').value='';run(calculate);$('#text').focus()};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#text').value);$('#copy').textContent='Copied';setTimeout(()=>$('#copy').textContent='Copy text',1800)}catch{output('Clipboard access unavailable. Select your text and copy it manually.')}};
$('#clean')?.addEventListener('click',()=>{$('#text').value=$('#text').value.split('\n').map(x=>x.replace(/[^\S\r\n]+/gu,' ').trim()).join('\n').trim();run(calculate);output('Text cleaned. Paragraph breaks preserved.');});
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{let t=$('#text').value;switch(b.dataset.case){case '0':t=t.toUpperCase();break;case '1':t=t.toLowerCase();break;case '2':t=t.toLowerCase().replace(/(^|\s)(\p{L})/gu,(_,a,c)=>a+c.toUpperCase());break;case '3':t=t.toLowerCase().replace(/(^\s*|[.!?]\s+)(\p{L})/gu,(_,a,c)=>a+c.toUpperCase());}$('#text').value=t;run(calculate)});
}else if(type==='weighted-grade'){
controls.innerHTML='<div id="rows"></div><div class="actions"><button type="button" id="add">Add assessment</button>'+button('calc','Calculate grade')+'</div>';
let seq=0;function add(score='',weight=''){seq++;let r=document.createElement('div');r.className='grade-row';r.innerHTML=`<label>Assessment<input type="text" value="Assessment ${seq}" aria-label="Assessment name"></label><label>Score (%)<input class="score" type="number" min="0" max="100" step="any" value="${score}"></label><label>Weight (%)<input class="weight" type="number" min="0" max="100" step="any" value="${weight}"></label><button class="remove" type="button" aria-label="Remove assessment">Remove</button>`;r.querySelector('button').onclick=()=>{r.remove();output('Assessment removed. Recalculate to update the result.')};$('#rows').append(r)}add(80,20);add(90,80);$('#add').onclick=()=>add();
calculate=()=>{let total=0,sum=0,rows=[...document.querySelectorAll('.grade-row')];if(!rows.length)throw Error('Add at least one assessment.');for(const r of rows){let a=r.querySelector('.score').value,b=r.querySelector('.weight').value;if(a===''||b==='')throw Error('Enter a score and weight in every row.');const s=pct(Number(a),'Score'),w=pct(Number(b),'Weight');if(!Number.isFinite(s)||!Number.isFinite(w))throw Error('Enter valid numbers.');sum+=s*w;total+=w;}if(total<=0||total>100.000001)throw Error('Combined weights must be above 0% and no more than 100%.');return output(`${fmt(sum/total)}% weighted average\nWeight entered: ${fmt(total)}%. Course points earned: ${fmt(sum/100)}.\n${total<99.999999?'This is the average of the entered portion, not your final course grade.':'All 100% of the course is included.'}`)};
}else if(type==='final-grade'){
controls.innerHTML='<div class="fields">'+field('current','Current average (%)',80)+field('target','Target grade (%)',85)+field('weight','Final exam weight (%)',40)+'</div>'+button('calc','Calculate required score');
calculate=()=>{let a=pct(number('current'),'Current average'),b=pct(number('target'),'Target'),w=pct(number('weight'),'Weight');if(w===0)throw Error('The final exam weight must be above zero.');let r=(b-a*(1-w/100))/(w/100);return output(`${fmt(r)}% required on the final\n(${b} − ${a} × ${fmt(1-w/100)}) ÷ ${w/100} = ${fmt(r)}\n${r>100?'This target is not achievable with an exam capped at 100%.':r<0?'Your target is already covered, assuming no minimum exam-pass rule.':'Check your course’s rounding and minimum exam rules.'}`)};
}else if(type==='percentage'){
controls.innerHTML='<div class="fields">'+select('mode','Calculation',[['of','A% of B'],['is','A is what % of B?'],['change','Change from A to B']])+field('a','A',20)+field('b','B',150)+'</div>'+button('calc','Calculate');
calculate=()=>{let a=number('a'),b=number('b'),m=$('#mode').value,r;if(m==='of'){r=a*b/100;return output(`${fmt(r)}\n${a} ÷ 100 × ${b} = ${fmt(r)}`)}if(m==='is'){if(b===0)throw Error('B cannot be zero when it is the base.');r=a/b*100;return output(`${fmt(r)}%\n${a} ÷ ${b} × 100 = ${fmt(r)}%`)}if(a<=0)throw Error('For change, the original value A must be greater than zero.');r=(b-a)/a*100;return output(`${fmt(r)}% change\n(${b} − ${a}) ÷ ${a} × 100 = ${fmt(r)}%`)};
}else if(type==='unit-converter'){
const units={length:{m:1,km:1000,cm:.01,mm:.001,in:.0254,ft:.3048,yd:.9144,mi:1609.344},mass:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.028349523125},temperature:{C:1,F:1,K:1}};
controls.innerHTML='<div class="fields">'+select('kind','Measurement',[['length','Length'],['mass','Mass'],['temperature','Temperature']])+field('value','Value',5)+select('from','From',[]) +select('to','To',[])+'</div>'+button('calc','Convert');
function populate(){let keys=Object.keys(units[$('#kind').value]);for(let id of ['from','to'])$('#'+id).innerHTML=keys.map(k=>`<option>${k}</option>`).join('');$('#to').selectedIndex=1;}populate();$('#kind').onchange=()=>{populate();run(calculate)};
calculate=()=>{let n=number('value'),k=$('#kind').value,a=$('#from').value,b=$('#to').value,r;if(k==='temperature'){let c=a==='F'?(n-32)*5/9:a==='K'?n-273.15:n;if(c< -273.1500001)throw Error('Temperature cannot be below absolute zero.');r=b==='F'?c*9/5+32:b==='K'?c+273.15:c}else{if(n<0)throw Error('Enter a non-negative length or mass.');r=n*units[k][a]/units[k][b]}if(!Number.isFinite(r))throw Error('Result is too large. Use smaller values.');return output(`${fmt(n)} ${a} = ${fmt(r)} ${b}\nRounded to at most six decimal places.`)};
}
$('#calc')?.addEventListener('click',()=>run(calculate));if(calculate)run(calculate);
controls.addEventListener('input',e=>{if(!['word-counter','reading-time','case-converter','text-cleaner'].includes(type))output('Inputs changed. Calculate to update your result.')});
if(document.modelContext?.registerTool&&['word-counter','reading-time','case-converter','text-cleaner'].includes(type)){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'set_tool_text',description:'Replace the visible text in the current ParhoDesk tool and update its count or timing.',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(typeof input?.text!=='string'||input.text.length>1000000)throw Error('Provide text up to one million characters.');$('#text').value=input.text;return run(calculate)}},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true})}catch{}}
}
