'use strict';
function calculateGpa({semester,courses,mode='cgpa',previous=[]}){
 const num=(value,label)=>{if(value===null||value===undefined||String(value).trim()===''||!Number.isFinite(Number(value)))throw Error('Enter a valid '+label+'.');return Number(value)};
 const grade=v=>{const n=num(v,'grade point or GPA');if(n<0||n>4)throw Error('Grade points and GPAs must be between 0 and 4.');return n};
 const credits=v=>{const n=num(v,'credit-hour value');if(n<=0)throw Error('Credit hours must be greater than zero.');return n};
 const sem=num(semester,'semester');if(!Number.isInteger(sem)||sem<1||sem>8)throw Error('Choose a semester from 1 to 8.');
 if(!Array.isArray(courses)||!courses.length)throw Error('Add at least one current-semester course.');
 let currentPoints=0,currentCredits=0,previousPoints=0,previousCredits=0;
 for(const c of courses){const g=grade(c.grade),h=credits(c.credits);currentPoints+=g*h;currentCredits+=h;}
 if(sem>1){if(!['cgpa','sgpa'].includes(mode))throw Error('Choose a previous-result method.');if(!Array.isArray(previous)||previous.length!==(mode==='cgpa'?1:sem-1))throw Error('Enter results for all previous semesters, or use your latest CGPA.');for(const p of previous){const g=grade(p.grade),h=credits(p.credits);previousPoints+=g*h;previousCredits+=h;}}
 const totalCredits=currentCredits+previousCredits,totalPoints=currentPoints+previousPoints;
 if(![totalCredits,totalPoints].every(Number.isFinite))throw Error('Credit totals are too large.');
 return {sgpa:currentPoints/currentCredits,cgpa:totalPoints/totalCredits,currentCredits,previousCredits,totalCredits,currentPoints,previousPoints,totalPoints};
}
if(typeof module!=='undefined')module.exports={calculateGpa};
if(typeof document!=='undefined'&&document.querySelector('[data-tool="gpa-calculator"]')){
 const controls=document.querySelector('#controls'),result=document.querySelector('#result');
 controls.innerHTML=`<div class="fields"><label>Current semester<select id="semester">${Array.from({length:8},(_,i)=>`<option value="${i+1}">Semester ${i+1}</option>`).join('')}</select></label></div><p class="gpa-note">Use grade points on a 4.00 scale, not percentage marks. Include only courses counted toward your institution’s GPA.</p><section id="history" hidden><h2>Previous results</h2><label>How would you like to enter your previous results?<select id="history-mode"><option value="cgpa">Latest CGPA + total previous credit hours</option><option value="sgpa">SGPA + credit hours for each previous semester</option></select></label><div id="cgpa-history" class="fields gpa-history"><label>Previous CGPA<input id="previous-cgpa" type="number" min="0" max="4" step="any" placeholder="e.g. 3.20"></label><label>Total previous GPA credit hours<input id="previous-credits" type="number" min="0.01" step="any" placeholder="e.g. 30"></label></div><div id="sgpa-history" hidden></div><p class="gpa-note">Use credits included in the reported GPA, not just passed or earned credits. For SGPA mode, enter every previous semester. One semester’s SGPA alone cannot represent several semesters.</p></section><h2>Current-semester courses</h2><div id="gpa-courses"></div><div class="actions"><button type="button" id="add-course">Add course</button><button type="button" id="calculate-gpa" class="primary">Calculate SGPA & CGPA</button></div>`;
 const q=s=>controls.querySelector(s);let serial=0;
 const stale=()=>{result.classList.remove('error');result.textContent='Enter your course results, then calculate to see your SGPA and total CGPA.'};
 function addCourse(){serial++;let row=document.createElement('div');row.className='grade-row gpa-course';row.innerHTML=`<label>Course name (optional)<input type="text" placeholder="Course ${serial}"></label><label>Grade points (0–4)<input class="course-grade" type="number" min="0" max="4" step="any" placeholder="e.g. 3.67"></label><label>Credit hours<input class="course-credits" type="number" min="0.01" step="any" placeholder="e.g. 3"></label><button type="button" class="remove" aria-label="Remove course ${serial}">Remove</button>`;row.querySelector('button').onclick=()=>{row.remove();stale()};q('#gpa-courses').append(row);stale()}
 function syncHistory(){let sem=Number(q('#semester').value),sgpa=q('#history-mode').value==='sgpa';q('#history').hidden=sem===1;q('#cgpa-history').hidden=sgpa;q('#sgpa-history').hidden=!sgpa;for(let i=1;i<=7;i++){let row=q(`[data-semester="${i}"]`);if(!row){row=document.createElement('div');row.className='fields prior-semester';row.dataset.semester=String(i);row.innerHTML=`<label>Semester ${i} SGPA<input class="prior-grade" type="number" min="0" max="4" step="any" placeholder="0.00–4.00"></label><label>Semester ${i} GPA credit hours<input class="prior-credits" type="number" min="0.01" step="any" placeholder="e.g. 15"></label>`;q('#sgpa-history').append(row)}row.hidden=i>=sem;}stale()}
 function calculate(){const semester=Number(q('#semester').value),mode=q('#history-mode').value;const courses=[...controls.querySelectorAll('.gpa-course')].map(r=>({grade:r.querySelector('.course-grade').value,credits:r.querySelector('.course-credits').value}));let previous=[];if(semester>1)previous=mode==='cgpa'?[{grade:q('#previous-cgpa').value,credits:q('#previous-credits').value}]:[...controls.querySelectorAll('.prior-semester')].filter(r=>!r.hidden).map(r=>({grade:r.querySelector('.prior-grade').value,credits:r.querySelector('.prior-credits').value}));try{const r=calculateGpa({semester,courses,mode,previous});result.classList.remove('error');result.innerHTML=`<div class="metrics"><div class="metric"><strong>${r.sgpa.toFixed(2)}</strong><span>Semester ${semester} SGPA</span></div><div class="metric"><strong>${r.cgpa.toFixed(2)}</strong><span>Total CGPA</span></div><div class="metric"><strong>${r.currentCredits}</strong><span>Current credits</span></div><div class="metric"><strong>${r.totalCredits}</strong><span>Total GPA credits</span></div></div><p class="gpa-formula">SGPA = ${r.currentPoints.toFixed(4)} quality points ÷ ${r.currentCredits} credits.<br>CGPA = (${r.previousPoints.toFixed(4)} previous + ${r.currentPoints.toFixed(4)} current quality points) ÷ ${r.totalCredits} total credits.</p><p class="gpa-note">${semester===1?'First semester: CGPA equals SGPA.':'Previous credits included: '+r.previousCredits+'. Previous GPA values may already be rounded, so the cumulative result is an estimate.'} Results are displayed to two decimal places; intermediate calculations are not rounded.</p>`;return r}catch(e){result.classList.add('error');result.textContent=e.message;return {error:e.message}}}
 q('#add-course').onclick=addCourse;q('#calculate-gpa').onclick=calculate;q('#semester').onchange=syncHistory;q('#history-mode').onchange=syncHistory;controls.addEventListener('input',stale);addCourse();addCourse();addCourse();syncHistory();
}
