'use strict';
function convertInteger(text,base){
 if(![2,8,10,16].includes(Number(base)))throw Error('Choose a supported base.');
 let s=String(text).trim().toUpperCase();if(!s)throw Error('Enter a number.');if(s.length>256)throw Error('Use up to 256 characters.');
 let sign=1n;if(s[0]==='-'||s[0]==='+'){if(s[0]==='-')sign=-1n;s=s.slice(1)}
 if(!s||![...s].every(c=>'0123456789ABCDEF'.indexOf(c)>=0&&'0123456789ABCDEF'.indexOf(c)<base))throw Error('Use only valid digits for the selected base. Enter integers without prefixes, spaces, or decimal points.');
 let value=0n;for(const c of s)value=value*BigInt(base)+BigInt('0123456789ABCDEF'.indexOf(c));value*=sign;
 return {value:value.toString(),binary:value.toString(2),octal:value.toString(8),decimal:value.toString(10),hex:value.toString(16).toUpperCase(),digits:s,base:Number(base),negative:sign<0n};
}
function attendance(attended,total,target,remaining=''){
 const integer=(v,label)=>{if(String(v).trim()===''||!Number.isSafeInteger(Number(v))||Number(v)<0||Number(v)>1000000)throw Error(label+' must be a whole number from 0 to 1,000,000.');return Number(v)};
 const a=integer(attended,'Attended classes'),t=integer(total,'Held classes');if(a>t)throw Error('Attended classes cannot exceed held classes.');
 const p=Number(target);if(String(target).trim()===''||!Number.isFinite(p)||p<=0||p>100||Math.abs(p*100-Math.round(p*100))>1e-7)throw Error('Target must be above 0 and at most 100, with up to two decimal places.');
 const scaled=Math.round(p*100),gap=scaled*t-10000*a;
 const needed=gap<=0?0:scaled===10000?null:Math.ceil(gap/(10000-scaled));
 const miss=Math.max(0,Math.floor((10000*a-scaled*t)/scaled));
 const left=String(remaining).trim()===''?null:integer(remaining,'Remaining classes');
 return {a,t,p,current:t?a/t*100:null,needed,miss,left,maxFinal:left===null||t+left===0?null:(a+left)/(t+left)*100,possible:left===null?null:10000*(a+left)>=scaled*(t+left)};
}
function creditAttendance({credits,weekly,weeks,attended,target,actual='',remaining=''}){
 const val=(x,label,min,max)=>{const n=Number(x);if(String(x).trim()===''||!Number.isFinite(n)||n<min||n>max||Math.abs(n*100-Math.round(n*100))>1e-7)throw Error(label+' must be between '+min+' and '+max+', with up to two decimal places.');return n};
 const credit=val(credits,'Course credits',.01,30),weekHours=val(weekly,'Weekly contact hours',.01,100);
 let held,completed=null;const override=String(actual).trim()!=='';
 if(override)held=val(actual,'Actual hours held',0,10000);
 else{completed=val(weeks,'Completed weeks',0,100);if(!Number.isInteger(completed))throw Error('Use whole completed weeks, or enter actual hours held for a partial week.');held=Math.round(weekHours*100)*completed/100;}
 const present=val(attended,'Hours attended',0,10000);if(present>held)throw Error('Hours attended cannot exceed hours held.');
 const left=String(remaining).trim()===''?'':Math.round(val(remaining,'Future hours remaining',0,10000)*100);
 const result=attendance(Math.round(present*100),Math.round(held*100),target,left);
 return {...result,credit,weekHours,completed,override,heldHours:held,attendedHours:present,neededHours:result.needed===null?null:result.needed/100,missHours:result.miss/100,leftHours:result.left===null?null:result.left/100};
}
function classCreditAttendance(values){
 const count=Number(values.classes),duration=Number(values.duration);
 if(String(values.classes).trim()===''||!Number.isSafeInteger(count)||count<0||count>100000)throw Error('Total classes attended must be a whole number from 0 to 100,000.');
 if(String(values.duration).trim()===''||!Number.isFinite(duration)||duration<=0||duration>12||Math.abs(duration*100-Math.round(duration*100))>1e-7)throw Error('Class duration must be above 0 and at most 12 hours, with up to two decimal places.');
 const attended=count*Math.round(duration*100)/100;
 const result=creditAttendance({...values,attended});
 return {...result,classes:count,duration,recoveryClasses:result.neededHours===null?null:Math.ceil(result.neededHours/duration-1e-10),missClasses:Math.floor(result.missHours/duration+1e-10)};
}
function makeExamPlan(start,exam,hours,text){
 const day=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('Choose valid dates.');const n=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==s)throw Error('Choose valid dates.');return n};
 const startMs=day(start),endMs=day(exam),days=(endMs-startMs)/86400000;
 if(days<1||days>365)throw Error('The exam must be 1–365 days after your start date.');
 if(String(hours).trim()===''||!Number.isFinite(Number(hours))||Number(hours)<.25||Number(hours)>12)throw Error('Daily study time must be between 0.25 and 12 hours.');
 const topics=String(text).split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!topics.length||topics.length>100||topics.some(x=>x.length>200))throw Error('Enter 1–100 topics, one per line, with up to 200 characters each.');
 const daily=Math.round(Number(hours)*60),studyDays=days>1?days-1:1,budget=daily*studyDays;
 if(topics.length>budget)throw Error('Too many topics for this study time. Group topics or allow more time.');
 const allocations=topics.map((name,i)=>({name,minutes:Math.floor(budget/topics.length)+(i<budget%topics.length?1:0)}));let ti=0,left=allocations[0].minutes;const schedule=[];
 for(let d=0;d<studyDays;d++){let free=daily,tasks=[];while(free>0&&ti<allocations.length){let take=Math.min(free,left);tasks.push({topic:allocations[ti].name,minutes:take});free-=take;left-=take;if(left===0){ti++;left=allocations[ti]?.minutes||0}}schedule.push({date:new Date(startMs+d*86400000).toISOString().slice(0,10),tasks})}
 if(days>1)schedule.push({date:new Date(endMs-86400000).toISOString().slice(0,10),tasks:[{topic:'Review all topics, practise recall, and revisit difficult questions',minutes:daily}]});
 return {days,daily,topics:topics.length,schedule,total:daily*days,revision:days>1};
}
if(typeof module!=='undefined')module.exports={convertInteger,attendance,creditAttendance,classCreditAttendance,makeExamPlan};
(()=>{if(typeof document==='undefined')return;const workspace=document.querySelector('.workspace');const names=['number-converter','cover-page-maker','exam-planner','attendance-calculator'];if(!workspace||!names.includes(workspace.dataset.tool))return;
 const type=workspace.dataset.tool,c=document.querySelector('#controls'),r=document.querySelector('#result');const q=s=>c.querySelector(s);const el=(tag,text,cls)=>{let n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 const input=(id,label,type='text',attrs='')=>`<label>${label}<input id="${id}" type="${type}" ${attrs}></label>`;
 const actions=label=>`<div class="actions"><button type="button" class="primary" id="calculate">${label}</button>${['cover-page-maker','exam-planner'].includes(type)?'<button type="button" id="print-result" disabled>Print / Save PDF</button>':''}</div>`;
 function message(text,error=false){r.classList.toggle('error',error);r.replaceChildren(el('p',text));workspace.classList.remove('print-ready');if(q('#print-result'))q('#print-result').disabled=true}
 function success(){r.classList.remove('error');r.replaceChildren();workspace.classList.add('print-ready');if(q('#print-result'))q('#print-result').disabled=false}
 function metric(label,value){const n=el('div',undefined,'metric');n.append(el('strong',value),el('span',label));return n}
 let calc;
 if(type==='number-converter'){
 c.innerHTML='<div class="fields">'+input('number','Number','text','placeholder="e.g. 101101" autocomplete="off" spellcheck="false"')+'<label>Input base<select id="base"><option value="2">Binary (2)</option><option value="8">Octal (8)</option><option value="10" selected>Decimal (10)</option><option value="16">Hexadecimal (16)</option></select></label></div><p class="gpa-note">Whole numbers, including negatives. Use digits only—no 0x / 0b prefixes. Negative results use a minus sign, not two’s complement.</p>'+actions('Convert number');
 calc=()=>{const out=convertInteger(q('#number').value,Number(q('#base').value));success();for(const [key,title] of [['binary','Binary (2)'],['octal','Octal (8)'],['decimal','Decimal (10)'],['hex','Hexadecimal (16)']]){const row=el('div',undefined,'conversion-row'),code=el('code',out[key]),copy=el('button','Copy '+title);copy.type='button';copy.onclick=async()=>{try{await navigator.clipboard.writeText(out[key]);copy.textContent='Copied'}catch{copy.textContent='Select the value to copy'}};row.append(el('strong',title),code,copy);r.append(row)}
 const details=el('details'),summary=el('summary','How the conversion works');details.append(summary);const d=[...out.digits].reverse();if(d.length<=20)details.append(el('p',(out.negative?'Apply a minus sign after converting the magnitude. ':'')+d.map((v,i)=>`${parseInt(v,16)} × ${out.base}^${i}`).reverse().join(' + ')+' = '+(out.negative?out.value.slice(1):out.value)));else details.append(el('p','For each digit, multiply its value by the input base raised to its position (rightmost position is 0), then add. Large integers are calculated exactly.'));
 let mag=BigInt(out.value);if(mag<0n)mag=-mag;let steps=[],v=mag;do{steps.push(`${v} ÷ 2 = ${v/2n}, remainder ${v%2n}`);v/=2n}while(v>0n&&steps.length<32);details.append(el('p','Decimal to binary: repeatedly divide the magnitude by 2. Read the remainders from bottom to top.'),el('pre',steps.join('\n')+(v>0n?'\n… steps shortened for display. The result above is complete.':'')));r.append(details)};
 }else if(type==='attendance-calculator'){
 c.innerHTML='<div class="fields"><label>Calculation method<select id="attendance-mode"><option value="hours">Course credit / contact hours</option><option value="classes">Class counts</option></select></label>'+input('target','Required attendance (%)','number','min="0.01" max="100" step="0.01" value="75"')+'</div><div id="attendance-hours"><div class="fields">'+input('credits','Course credit hours','number','min="0.01" max="30" step="0.01" value="3"')+input('weekly','Scheduled contact hours per week','number','min="0.01" max="100" step="0.01" value="3"')+input('weeks','Completed teaching weeks','number','min="0" max="100" step="1" placeholder="e.g. 10"')+input('classes-attended','Total number of classes attended','number','min="0" step="1" placeholder="e.g. 16"')+input('class-duration','Duration of each class (hours)','number','min="0.01" max="12" step="0.01" value="1"')+input('actual-hours','Actual hours held (optional override)','number','min="0" step="0.01" placeholder="For cancellations or partial weeks"')+input('remaining-hours','Future contact hours remaining (optional)','number','min="0" step="0.01" placeholder="Leave blank if unknown"')+'</div><p class="gpa-note">Weekly contact hours start equal to course credits as a planning assumption. Adjust them to your timetable, especially for labs. Attended hours = classes attended × duration per class. Enter 1.5 for a 90-minute class. This assumes every counted class has the same duration; use a representative exact average only if you know the actual total time.</p><p id="hours-basis" class="gpa-note">Estimated hours held = scheduled weekly contact hours × completed teaching weeks. Enter actual hours held to override this estimate.</p></div><div id="attendance-classes" hidden><div class="fields">'+input('attended','Classes attended','number','min="0" step="1" placeholder="e.g. 18"')+input('held','Classes held so far','number','min="0" step="1" placeholder="e.g. 25"')+input('remaining','Future classes remaining (optional)','number','min="0" step="1" placeholder="Leave blank if unknown"')+'</div></div>'+actions('Calculate attendance');
 q('#attendance-mode').onchange=()=>{const hours=q('#attendance-mode').value==='hours';q('#attendance-hours').hidden=!hours;q('#attendance-classes').hidden=hours;};
 q('#credits').addEventListener('input',()=>{q('#weekly').value=q('#credits').value;});
 q('#actual-hours').addEventListener('input',()=>{q('#weeks').disabled=q('#actual-hours').value.trim()!=='';q('#hours-basis').textContent=q('#weeks').disabled?'Actual hours held will be used. Completed weeks are not needed.':'Estimated hours held = scheduled weekly contact hours × completed teaching weeks.';});
 calc=()=>{const hours=q('#attendance-mode').value==='hours';const a=hours?classCreditAttendance({credits:q('#credits').value,weekly:q('#weekly').value,weeks:q('#weeks').value,classes:q('#classes-attended').value,duration:q('#class-duration').value,target:q('#target').value,actual:q('#actual-hours').value,remaining:q('#remaining-hours').value}):attendance(q('#attended').value,q('#held').value,q('#target').value,q('#remaining').value);success();const metrics=el('div',undefined,'metrics');metrics.append(metric('Current attendance',a.current===null?'Not started':a.current.toFixed(2)+'%'),metric('Required attendance',a.p+'%'));if(hours){metrics.append(metric('Classes attended',String(a.classes)),metric('Hours attended / held',a.attendedHours+' / '+a.heldHours));}r.append(metrics);
 if(hours)r.append(el('p',`Course: ${a.credit} credit hours. ${a.override?'Using your actual hours held.':`Estimated contact hours held: ${a.weekHours} hours/week × ${a.completed} weeks = ${a.heldHours} hours.`} Attended time: ${a.classes} classes × ${a.duration} hours = ${a.attendedHours} hours. Attendance = ${a.attendedHours} ÷ ${a.heldHours} × 100${a.heldHours?' = '+a.current.toFixed(2)+'%.':'; undefined until teaching begins.'}`));
 const needed=hours?a.neededHours:a.needed,miss=hours?a.missHours:a.miss,unit=hours?'contact hours':'classes',format=x=>hours?x.toFixed(2):String(x);
 if(needed===null)r.append(el('p','A 100% target cannot be recovered after missed attendance if those absences remain in the record.'));else if(needed>0)r.append(el('p',`Attend the next ${format(needed)} ${unit} without any further absence to reach at least ${a.p}%.`));else r.append(el('p',a.t?`You meet the target. You can miss up to ${format(miss)} consecutive upcoming ${unit} before dropping below it, assuming no attended teaching in between.`:'No attendance percentage exists yet. Attend your first session to establish a record.'));
 if(hours&&a.current!==null&&a.neededHours!==null)r.append(el('p',a.recoveryClasses>0?`At ${a.duration} hours per class, attend ${a.recoveryClasses} whole consecutive classes to recover.`:`At ${a.duration} hours per class, you can miss ${a.missClasses} whole consecutive classes while meeting the target.`));
 if(a.left!==null)r.append(el('p',a.maxFinal===null?'No held or future teaching entered.':`If you attend all ${format(hours?a.leftHours:a.left)} remaining ${unit}, final attendance will be ${a.maxFinal.toFixed(2)}%. ${a.possible?'The target is reachable.':'The target is not reachable within that remaining teaching time.'}`));
 r.append(el('p',hours?'Time-based estimate: each contact hour has equal weight. Required recovery time is rounded up to 0.01 hour; allowable missed time is rounded down. Actual sessions may be longer, so attend whole required sessions. Credits alone do not determine attendance; confirm your institution counts hours rather than sessions.':'Assumes all classes count equally. Check separate lab, subject, and approved-leave rules with your institution.'))};
 }else if(type==='cover-page-maker'){
 c.innerHTML='<div class="fields">'+input('institution','Institution (optional)','text','maxlength="120" placeholder="University / college"')+input('department','Department (optional)','text','maxlength="120"')+input('assignment','Assignment title','text','maxlength="180" placeholder="Assignment 1"')+input('subject','Subject / course','text','maxlength="120"')+input('student','Student name','text','maxlength="120"')+input('roll','Roll number','text','maxlength="60"')+input('teacher','Submitted to (optional)','text','maxlength="120"')+input('semester','Semester / section (optional)','text','maxlength="60"')+input('submission','Submission date (optional)','date')+'</div>'+actions('Create cover page')+'<p class="gpa-note">After creating the preview, choose Print / Save PDF and select Save as PDF in your browser. For a clean page, turn off browser headers and footers.</p>';
 calc=()=>{const v=id=>q('#'+id).value.trim();for(const id of ['assignment','subject','student','roll'])if(!v(id))throw Error('Fill in the assignment title, subject, student name, and roll number.');success();const paper=el('article',undefined,'cover-paper');if(v('institution'))paper.append(el('h2',v('institution'),'cover-institution'));if(v('department'))paper.append(el('p',v('department'),'cover-department'));paper.append(el('div','ASSIGNMENT','cover-label'),el('h1',v('assignment')),el('p',v('subject'),'cover-subject'));const data=el('dl');for(const [id,label] of [['student','Submitted by'],['roll','Roll number'],['teacher','Submitted to'],['semester','Semester / section'],['submission','Submission date']])if(v(id)){data.append(el('dt',label),el('dd',v(id)))}paper.append(data);r.append(paper)};
 }else{
 const today=new Date(),localDate=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
 c.innerHTML='<div class="fields">'+input('exam-name','Subject / exam name','text','maxlength="120" placeholder="e.g. Linear Algebra"')+input('start-date','Study start date','date',`value="${localDate}"`)+input('exam-date','Exam date','date')+input('daily-hours','Study hours per day','number','min="0.25" max="12" step="0.25" value="2"')+'</div><label for="topics">Topics / chapters (one per line)</label><textarea id="topics" placeholder="Vectors and span\nSystems of equations\nMatrix transformations"></textarea><p class="gpa-note">Time is divided equally across topics, in your chosen order. The exam day is excluded. With two or more study days, the last day is reserved for revision. Daily time is focused study time; take breaks separately.</p>'+actions('Create exam plan');
 calc=()=>{const name=q('#exam-name').value.trim();if(!name)throw Error('Enter the subject or exam name.');const p=makeExamPlan(q('#start-date').value,q('#exam-date').value,q('#daily-hours').value,q('#topics').value);success();const plan=el('article',undefined,'exam-plan');plan.append(el('h2',name+' — Preparation plan'),el('p',`Exam: ${q('#exam-date').value} · ${p.days} study days · ${p.daily} minutes/day · ${p.topics} topics · ${p.total} minutes in total`),el('p',p.revision?'The last study day is reserved for revision. Time allocation is equal, not a prediction of how long each topic requires.':'One study day available: no separate revision day. Reserve some of your topic time for recall.'));const table=el('table'),head=el('thead'),hr=el('tr');for(const h of ['Date','Study tasks','Minutes']){const th=el('th',h);th.scope='col';hr.append(th)}head.append(hr);table.append(head);const body=el('tbody');for(const day of p.schedule){let tr=el('tr'),tasks=el('td');for(const task of day.tasks)tasks.append(el('p',`${task.topic} — ${task.minutes} min`));tr.append(el('td',day.date),tasks,el('td',String(p.daily)));body.append(tr)}table.append(body);plan.append(table);r.append(plan)};
 }
 q('#calculate').onclick=()=>{try{calc()}catch(e){message(e.message,true)}};if(q('#print-result'))q('#print-result').onclick=()=>window.print();c.addEventListener('input',()=>message('Inputs changed. Generate a new result to update the preview.'));c.addEventListener('change',()=>message('Inputs changed. Generate a new result to update the preview.'));message('Fill in your details above to get started.');
})();
